# Node.js with Angular
# Build a Node.js project that uses Angular.
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g @angular/cli
      npm install
      ng build --prod
    displayName: 'npm install and build'

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Azure subscription 1 (78f150c1-9576-4d65-a77d-01d366a886c8)'
      appType: 'webApp'
      WebAppName: 'pokemon-frontend'
      packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
